service/routes.py
tests/test_routes.py

Update root URL response to return JSON information

Add root URL response

---

service/models/shopcart.py
service/routes.py
tests/factories.py
tests/test_item.py
tests/test_routes.py
tests/test_shopcart.py

Fixed bugs for:
- items' subfactory case
- items' factory naming
Added:
- List routes (without test cases)

fixed-db-bugs

---

service/routes.py
tests/test_routes.py

Added:
- routes: api for create a shopcart
- test_routes: for testing the create
Note:
- the test case fail because we do not have "read" api now

added create routes and test cases

---

service/routes.py
tests/test_routes.py

- Added delete_shopcarts endpoint
- Added test_delete_shopcart and test_delete_non_exist_shopcart

Add delete_shopcarts endpoint and corresponding tests

---

service/routes.py
tests/test_routes.py

Added update_a_particular_shopcarts endpoint
Added test_update_shopcart and test_update_nonexistent_shopcart

Update a particular shopcart

---

service/routes.py
tests/test_item.py
tests/test_routes.py

Added:
- route("/shopcarts/<int:shopcart_id>/items", methods=["POST"])
- test_add_item(self), test_serialize_a_item(self), test_deserialize_a_item(self)

added create item api

---

tests/test_item.py
tests/test_routes.py

Add:
three test cases about error_handlers
Modify:
read an item in test_item.py

modified read an item in test_item.py and add three test cases

---

service/routes.py
tests/test_item.py
tests/test_routes.py

added tests and endpoint for deleting an item from the shopcart

---

README.md
tests/test_item.py

- 95% coverage reached
- **merge postponed** until all necessary tests are added

Coverage Improvement, Bug Fix and README Update

---

service/routes.py
tests/test_item.py
tests/test_routes.py

[Zenhub](https://app.zenhub.com/workspaces/shopcarts-fa24-001-66e8cc2f4e5313001e251e62/issues/gh/csci-ga-2820-fa24-001/shopcarts/6)
resolves #6 
PR for Update items in a cart.

Update items in a cart

---

tests/test_item.py

one last issue remained, see below ouput from `make lint`:
```
************* Module tests.test_cli_commands
tests/test_cli_commands.py:1:0: R0801: Similar lines in 2 files
==tests.test_item:[25:52]
==tests.test_shopcart:[28:55]
app.config["TESTING"] = True
app.config["DEBUG"] = False
app.config["SQLALCHEMY_DATABASE_URI"] = DATABASE_URI
app.logger.setLevel(logging.CRITICAL)
app.app_context().push()
@classmethod
def tearDownClass(cls):
"""This runs once after the entire test suite"""
db.session.close()
def setUp(self):
"""This runs before each test"""
db.session.query(Shopcart).delete()  # clean up the last tests
db.session.query(Item).delete()  # clean up the last tests
db.session.commit()
def tearDown(self):
"""This runs after each test"""
db.session.remove() …
```

Fixed some docstring and init issues

---

service/routes.py
tests/test_item.py
tests/test_routes.py

Added:
- one sad path for create item
- fixed update routes error
- added update item model test case 
- added completed routes info

Fixed bugs

---

.github/workflows/ci.yml
README.md

resolves #49 
Added badges to README
Notes:
- I had to set `poetry config virtualenvs.create true` in the Install dependencies step. (poetry wouldn't install otherwise)
- Running commands within poetry env.
- Build fails on the third linting command: `poetry run pylint service tests --max-line-length=127` (**Excluding it for now**, created a new issue #52)

CI actions

---

README.md
service/routes.py
tests/test_routes.py

1. Added the CLEAR action route
2. Added the test case
3. Added the readme file info

Add clear action

---

poetry.lock
service/models/shopcart.py
service/routes.py
tests/test_routes.py
tests/test_shopcart.py

1. Add calculate total price
2. Add calculate selected price

Calculate-Total-Price

---

poetry.lock
service/models/shopcart.py
service/routes.py
tests/test_routes.py
tests/test_shopcart.py

Reverts CSCI-GA-2820-FA24-001/shopcarts#59

Revert "Revert "Calculate-Total-Price""

---

service/models/shopcart.py
service/routes.py
tests/test_routes.py
tests/test_shopcart.py

1. Add calculate total price
2. Add calculate selected price

Calculate-item-price

---

service/models/item.py
service/routes.py
tests/test_item.py
tests/test_routes.py

1. add query for item list
2. modify test_list_items_in_shopcart function to suit for query

add query for item list

---

features/shopcarts.feature
features/steps/shopcarts_steps.py
service/static/js/rest_api.js

fixed bdd bugs

---

service/routes.py

fixed routes bugs

---

README.md

fixed evt bugs
